// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFVZXb5eDCYTquramz-SNSsUi0gSDFmLU',
    appId: '1:419767925638:android:7b425564a4310204d00a07',
    messagingSenderId: '419767925638',
    projectId: 'prince-test-app',
    storageBucket: 'prince-test-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmSvCk52X3_-hhsMblpdLiuXR81PTjYuA',
    appId: '1:419767925638:ios:19873755e12eb618d00a07',
    messagingSenderId: '419767925638',
    projectId: 'prince-test-app',
    storageBucket: 'prince-test-app.appspot.com',
    iosBundleId: 'io.princesworld.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmSvCk52X3_-hhsMblpdLiuXR81PTjYuA',
    appId: '1:419767925638:ios:c6fb51ba86d9fc0ed00a07',
    messagingSenderId: '419767925638',
    projectId: 'prince-test-app',
    storageBucket: 'prince-test-app.appspot.com',
    iosBundleId: 'io.princesworld.testapp.RunnerTests',
  );
}
